### ISSUE TITLE
enableActivityTracking() doesn't work in synchronous JavaScript Tracker

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#3] opened 2013-07-07 18:46 UTC
See screenshot. Suspect it's being called before DOM has finalised or something like that...
![capture](https://f.cloud.github.com/assets/200511/478454/ba08042a-b7fa-11e2-91a9-305977eebe9a.png)

**Comment by fblundun** [comment] 2016-04-19 14:39
I couldn't reproduce this. Closing since this was probably fixed unknowingly at some point in the last three years...

**Closed by fblundun** 2016-04-19 14:39 UTC
Labels: Bug

**Comment by alexanderdean** [comment] 2016-04-19 18:54
7 Jul 2013! Incredibly old ticket
