### ISSUE TITLE
Browser based geolocation?

### ISSUE THREAD

**Issue by agentgt** [snowplow/snowplow-javascript-tracker#305] opened 2014-12-18 18:17 UTC
It appears the snowplow trackers doesn't have anyway to take advantage of [HTML5 browser geolocation](http://www.w3.org/TR/geolocation-API/).

I realize that there probably is some difficulty in doing this correctly in that the tracker will kick off before you can gather that data but it would be nice to know how others are implementing this.

**Comment by alexanderdean** [comment] 2015-03-03 16:50
Duplicate of #191

**Closed by alexanderdean** 2015-03-03 16:50 UTC
Labels: New Context
