### ISSUE TITLE
HTTP 413 response from the CloudFront collector

### ISSUE THREAD

**Issue by yuvalherziger** [snowplow/snowplow-javascript-tracker#368] opened 2015-04-17 09:33 UTC
Problem raised due to an average of 17% less distinct visits than in GA.
The following thread elaborates on the details: 
https://groups.google.com/forum/#!topic/snowplow-user/rdMtt8vQwlY

Could be related to respectDoNotTrack, might as well be a coincidence, but the important thing is that for a given browser, it was resolved by clearing the cache.

**Comment by yuvalherziger** [comment] 2015-04-20 11:03
Caused by this issue:
https://github.com/snowplow/snowplow-javascript-tracker/issues/362

**Comment by alexanderdean** [comment] 2015-04-20 11:14
Closing as duplicate of #362.

**Closed by alexanderdean** 2015-04-20 11:14 UTC
