### ISSUE TITLE
Document the fact that PRs from users outside the Snowplow organization will fail travis

### ISSUE THREAD

**Issue by chrissherlock** [snowplow/snowplow-javascript-tracker#616] opened 2017-10-19 08:22 UTC
All recent Travis builds have been failing with the following:

```
Running "intern:functional" (intern) task
Listening on 0.0.0.0:9000
Error: Tunnel failed to start: Exit code: 1
  at handleChildExit  <node_modules/digdug/Tunnel.js:336:16>
  at Socket.<anonymous>  <node_modules/digdug/Tunnel.js:379:6>
  at emitOne  <events.js:82:20>
  at Socket.emit  <events.js:169:7>
  at Pipe._onclose  <net.js:469:12>
Warning: Test failure; check output above for details. Use --force to continue.
Aborted due to warnings.
The command "grunt travis" exited with 3.
```

**Comment by BenFradet** [comment] 2017-10-19 08:25
The CI is very fiddly, but I don't think it fails every time.

**Comment by chrissherlock** [comment] 2017-10-19 08:25
I could be wrong, but all the pull requests have failed so far :(

**Comment by chuwy** [comment] 2017-10-19 14:18
That's fine @chrissherlock. Our CI/CD works properly only on PR pushed by us. I don't see how this can prevent PRs to be merged.

**Comment by chrissherlock** [comment] 2017-10-20 06:54
Thanks, can you perhaps make this a bit more clear somewhere though?

**Comment by BenFradet** [comment] 2017-10-20 08:31
That's a great point, adjusting the ticket's name to reflect that.

**Comment by paulboocock** [comment] 2020-02-07 15:53
Duplicate of #606

**Closed by paulboocock** 2020-02-07 15:53 UTC
Labels: category:setup, priority:low, status:need_triage, type:documentation, type:internal
