### ISSUE TITLE
Discover cause of "cuckoo events"

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#373] opened 2015-06-11 12:38 UTC
We have had a couple of clients who have reported valid Snowplow events generated on a different website (i.e. not one in their network) landing on their collector. Let's call these stray events from an unrelated third-party ["cuckoo events"](http://www.bbc.co.uk/nature/28038684).

My original thinking was that there was some kind of conflict between perhaps two different trackers running on the site (e.g. one tracker is embedded in an ad unit). But from talking to these users, this doesn't seem likely.

My new theory is around local storage. Conceivably the cuckoo's event gets written to local storage, then the browser switches to a new website and this new website is also running Snowplow, sees the event in local storage and sends it to the wrong collector.

In theory this shouldn't happen - local storage is meant to be sandboxed to the domain...

Cuckoo events are very rare, but frustrating for users when they happen.

**Comment by fblundun** [comment] 2015-06-11 13:15
That is odd!

If we can't find the cause, we could work around the problem by incorporating the domain in the localStorage queue and only sending localStorage events from the correct domain.

**Comment by benhoyt** [comment] 2015-06-11 13:37
(For reference, I'm one of those customers getting the odd stray event like.)

While it’d be nice to know how these events are getting in (and preventing that if possible), I don’t actually think is the right solution. Other people's collector endpoints are public URLs, so anyone can send any data to any collector. Even if you plug one hole, there's always going to be another way that the odd event somehow goes to the wrong collector, whether it's developer testing, malicious behavior, browser bugs, or whatever.

We don't really care about 1 or 2 stray events coming in from another site. But what *is* a bit painful is that our nightly automated script to run Snowplow storage-loader fails hard, so we have to dig into the problem, figure out what’s happening, delete the stray events in shredded events S3 bucket, and re-run manually. It would be much nicer if the Snowplow process (maybe at the EmrEtlRunner level?) simply ignored events or schemas it wasn’t looking for.

Thoughts? How would this work? Could you specify in the EmrEtlRunner config a whitelist of schemas you care about, and anything else would be ignored instead of shredded?

**Comment by alexanderdean** [comment] 2015-06-11 13:41
Thanks for your thoughts Ben! Companion ticket created to continue the whitelist conversation: https://github.com/snowplow/snowplow/issues/1768

**Comment by paulboocock** [comment] 2021-04-09 17:56
We've not seen any discussion around this for 6 years now, so I'm going to close this one. I'll happily reopen if we ever get a repro, but until then I'm not sure there is much else we can do beyond looking at adding additional entropy to the localStorage queue name which shouldn't be required (perhaps this was some poor implementation in browsers from 6 years ago, it certainly wouldn't surprise me!)

**Closed by paulboocock** 2021-04-09 17:56 UTC
Labels: category:help_wanted, priority:low, status:need_triage, type:defect
