### ISSUE TITLE
Offer localStorage as an alternative to cookies?

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#507] opened 2016-08-10 09:20 UTC
We have a user that's run into issues because there are so many cookies on their main domain that some of these get randomly dropped. From the user:

> We currently have two problems:
> 1. total size on one domain, especially the top level .mycompany.com
which is limited on some (mobile) browsers.  The limit is specific on
each (sub) domain.
> 2. The overall http header size. Most servers only allow up to 4kb
(Akamei default). We increased it on some of our servers to 16kb but
still the limit of some user's  accumulated  cookies on one request.
Having such big http headers increase the total size of all upstream
requests and binds a lot of memory on servers requests and therefore
reduces the number of possible concurrent connections.

The client suggested using `localStorage` as a work around. Is this feasible? Is it desirable?

**Comment by alexanderdean** [comment] 2016-08-10 09:20
Duplicate of #506

**Closed by alexanderdean** 2016-08-10 09:20 UTC

**Comment by bogaert** [comment] 2017-03-03 07:43
![](https://github.trello.services/images/mini-trello-icon.png) [Product ~ Add support for tracking client session and device in localStorage rather than cookies](https://trello.com/c/MOrjnPkU/1-product-add-support-for-tracking-client-session-and-device-in-localstorage-rather-than-cookies)
