### ISSUE TITLE
Include DOM event in context generator args

### ISSUE THREAD

**Issue by sreynen** [snowplow/snowplow-javascript-tracker#1386] opened 2024-11-20 20:40 UTC
**Is your feature request related to a problem? Please describe.**
I have various buttons on a page that need different contexts associated with their click events. I can attach the context to the button DOM element, but I don't see any way to get that DOM element from my context generator.

**Describe the solution you'd like**
I would like the `event` associated with the click to be passed as a parameter to the context generator function. I can see it's being captured here: https://github.com/snowplow/snowplow-javascript-tracker/blob/master/plugins/browser-plugin-button-click-tracking/src/api.ts#L99C10-L99C22 but it's not passed into the context generator, so can't be used.

**Describe alternatives you've considered**
The `elem` would also work for my needs, but the `event` seems more flexible.

**Additional context**
None.

**Comment by matus-tomlein** [comment] 2024-11-21 08:20
Closing as I think this is a duplicate of #1368. Please correct me if I'm wrong. Note that the event is already being passed, but the element is not.

**Closed by matus-tomlein** 2024-11-21 08:20 UTC
Labels: type:enhancement
