### ISSUE TITLE
Snowplow in Mobile.

### ISSUE THREAD

**Issue by Rohit261189** [snowplow/snowplow-javascript-tracker#400] opened 2015-07-29 06:25 UTC
Can we use snowplow in Android and iOS hybrid Application?
considering the fact, mobile app is a Phone-gap application, using JavaScript  for coding functionality.
I am using JavaScript Tracker.
Please Revert ASAP.

**Comment by alexanderdean** [comment] 2015-07-29 07:43
Duplicate of #107

**Closed by alexanderdean** 2015-07-29 07:43 UTC
