### ISSUE TITLE
Exception raised when using extensions like Ghostery

### ISSUE THREAD

**Issue by emattiazzi** [snowplow/snowplow-javascript-tracker#639] opened 2018-02-28 15:09 UTC
Hello, 
I've noticed that the JavaScript tracker is using Optimizely. 
When the user uses extensions like Ghostery an exception is raised and is not catched. 

```
TypeError: ak.optimizely.get is not a function
    at aH (http://d1fc8wv8zag5ca.cloudfront.net/2.8.0/sp.js:63:290)
```

Ghostery is not blocking Snowplow but it's blocking Optimizely. 

I suggest that instead of checking only if Optimizely is present on the window inside [tracker.js](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L1002) to check if also the needed method is present or catch the exceptions.

**Comment by alexanderdean** [comment] 2018-02-28 15:28
Duplicate of #619

**Closed by alexanderdean** 2018-02-28 15:28 UTC
