### ISSUE TITLE
Make sure that web page ID gets reset with every `trackPageView` call

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#508] opened 2016-08-24 08:01 UTC
A `webPage context ID` is generated with each page view. This is used in the data modeling step to identify what page view a subsequent on-page event occurred on. (Particularly useful if a user has multiple pages open in their browser simultaneously, and you want to know which tab a particular event happened in.)  This is generated if the `webpage` context is set to `true` when initializing the JS tracker.

Currently, it appears that the ID is generated *when the tracker is initialized*. This is the incorrect behaviour: it should be generated when the `trackPageView` method is called. As a result, the context does not currently work with single page webapps, because it is not reset with each 'virtual' page view.

**Comment by alexanderdean** [comment] 2016-08-24 08:20
See also #500

**Comment by alexanderdean** [comment] 2016-08-24 08:21
Duplicate of #436

**Closed by alexanderdean** 2016-08-24 08:21 UTC
