### ISSUE TITLE
Investigate domain_sessionid not being set

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#464] opened 2016-03-03 14:39 UTC
E.g. see the following example bad row:

``` json
{
  "_index": "trials",
  "_type": "bad_rows",
  "_id": "AVLwXAfBO-JJeYbnt3cO",
  "_score": null,
  "_source": {
    "line": "2016-02-12\t20:58:23\t-\t43\t150.70.188.176\tGET\t150.70.188.176\t/i\t200\t-\tMozilla%2F4.0+%28compatible%3B+MSIE+8.0%3B+Windows+NT+5.1%3B+Trident%2F4.0%29\te=pv&url=http%3A%2F%2Ftheculturetrip.com%2Fnorth-america%2Fusa%2Falabama%2Farticles%2Feating-out-in-orange-beach-al-top-10-restaurants%2F%3Futm_source%3Demails%26utm_medium%3Dexternal%26utm_campaign%3D281014alabamafood&page=Eating%20Out%20in%20Orange%20Beach%2C%20AL%3A%20Top%2010%20Restaurants&tv=js-2.5.2&tna=co&aid=the_culture_trip20160105&p=web&tz=America%2FChicago&lang=en-us&cs=UTF-8&res=320x568&cd=32&cookie=1&eid=82834d1b-eb9e-49c0-81cc-e601bf59d40f&dtm=1455310673489&vp=320x460&ds=320x9079&vid=1&sid=&cv=clj-1.0.0-tom-0.2.0&nuid=0f538ce3-e1bd-4881-bec9-0a36ded60530\t-\t-\t-\t-\t-",
    "errors": [
      {
        "level": "error",
        "message": "Field [sid]: [] is not a valid UUID"
      }
    ],
    "failure_tstamp": "2016-02-17T16:56:16.603Z"
  },
  "fields": {
    "failure_tstamp": [
      1455728176603
    ]
  },
  "sort": [
    1455728176603
  ]
}
```

Note that the `sid` appears to be totally blank - I thought we checked for nulls / empty values before sending?

**Comment by alexanderdean** [comment] 2016-04-19 08:00
Assigning to @fblundun

**Comment by fblundun** [comment] 2016-06-02 13:27
I can't reproduce this, or see how it can happen - is it still happening in production?

**Comment by fblundun** [comment] 2016-06-14 17:07
Pushing back...

**Comment by yalisassoon** [comment] 2016-09-22 10:25
Need to validate that this is is still happening before actioning

**Comment by paulboocock** [comment] 2020-02-07 17:26
No movement in 3 years. Guessing it probably isn't an issue any more...

**Closed by paulboocock** 2020-02-07 17:26 UTC
Labels: type:defect
