### ISSUE TITLE
Mapping of new `domain_sessionid` <-> `domain_userid || '-' || domain_sessionidx` is not 1-to-1

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#387] opened 2015-07-09 09:56 UTC
E.g. 12% of sessions identified by the new `domain_sessionid` field have more than one corresponding combination of concatenated `domain_userid || '-' || domain_sessionidx` values:

```sql
select	
number_of_sessions_old_definition,	
count(*) as frequency	
from (	
	select
	domain_sessionid,
	count(distinct(domain_userid || '-' || domain_sessionidx)) AS number_of_sessions_old_definition
	from atomic.events
	where collector_tstamp > '2015-07-07'
	and domain_sessionid is not null
	group by 1
) t	
group by 1	
order by 1;	
```

Returns:

```
1	1742
2	159
3	32
4	22
5	10
6	5
7	2
8	2
9	1
12	1
```

A smaller % (4%) of sessions identified using the old `domain_userid || '-' || domain_sessionidx` combination of fields have more than one corresponding value for `domain_sessionidx`:

```sql
select	
number_of_sessions_new_definition,	
count(*) as frequency	
from (	
	select
	domain_userid || '-' || domain_sessionidx,
	count(distinct(domain_sessionid)) AS number_of_sessions_new_definition
	from atomic.events
	where collector_tstamp > '2015-07-07'
	and domain_sessionid is not null
	group by 1
) t	
group by 1	
order by 1;	
```

Returns:

```
1	2167
2	78
3	2
4	4
5	1
6	1
8	1
11	1
```

So it looks like there's a bigger issue regarding sessions identified with the new `domain_sessionid` field having more than one corresponding value of `domain_userid` and `domain_sessionidx`. We can inspect the data manually using the following query:

```sql
select		
t1.domain_sessionid,		
domain_userid,		
domain_sessionidx		
from (		
	select	
	domain_sessionid, 	
	count(*)	
	from (	
		select 
		domain_sessionid,
		domain_userid,
		domain_sessionidx
		from atomic.events
		where collector_tstamp > '2015-07-06'
		and domain_sessionidx is not null
		group by 1,2,3
	)	
	group by 1	
	having count(*) > 1	
) t1		
join (		
		select 
		domain_sessionid,
		domain_userid,
		domain_sessionidx
		from atomic.events
		where collector_tstamp > '2015-07-06'
		and domain_sessionidx is not null
		group by 1,2,3
) t2		
on t1.domain_sessionid = t2.domain_sessionid		
order by 1,2,3		
```
Example return result set:

```
00d7235e-0f21-4c25-8aa9-964c69b32805	990e43c88388f342	1
00d7235e-0f21-4c25-8aa9-964c69b32805	990e43c88388f342	2
00d7235e-0f21-4c25-8aa9-964c69b32805	990e43c88388f342	3
00d7235e-0f21-4c25-8aa9-964c69b32805	990e43c88388f342	4
013e8083-3a63-472d-bf86-2e1bbd796c5f	035911bad39267b4	1
013e8083-3a63-472d-bf86-2e1bbd796c5f	035911bad39267b4	2
013f1501-69b0-4c73-a7dd-f764f874ea9d	db4a0605c3c9edf8	1
013f1501-69b0-4c73-a7dd-f764f874ea9d	db4a0605c3c9edf8	2
01400e64-ba1a-499d-90c2-79646e8bfaf1	c76924a2aaa525e3	2
01400e64-ba1a-499d-90c2-79646e8bfaf1	c76924a2aaa525e3	3
01400e64-ba1a-499d-90c2-79646e8bfaf1	c76924a2aaa525e3	4
```

Under what circumstances do we think the `domain_sessionidx` would increment *without* the `domain_sessionid` value changing?

If we think this is likely because of a fault with the `domain_sessionid` - should maybe hold off on the next JS release. If we think it's more likely an issue with `domain_sessionidx`, better to release soon - the new data point will be invaluable in helping us debug the old.

What do you think @fblundun and @alexanderdean ?

**Comment by alexanderdean** [comment] 2015-07-09 10:01
Huge analysis @yalisassoon ! Interested to hear Fred's thoughts...

**Comment by fblundun** [comment] 2015-07-09 10:58
I managed to reproduce multiple vids for a single sid as follows (assume no cookies exist to begin with):

Open tab A and fire an event there
 - vid=1 is generated and new sid is generated. Both are stored in the cookie; sid is also stored as a JS variable.
 - session cookie is set
Leave tab A, keeping it open
Wait for the session cookie to expire
Open tab B and fire an event there
 - session cookie not detected so vid increments to 2 and new sid is generated. Both are stored in the cookie.
 - session cookie is set
Go back to tab A and fire an event there
 - session cookie is detected so incremented vid (2) is loaded from cookie
 - the sid is treated differently: the tracker sees that the session cookie already exists so assumes that it is still on the same session and can use the session ID JS variable rather than the session ID from the cookie. So we have the old sid but a new vid.

The mistake was to assume that if the session cookie exists, the session ID variable doesn't need to be updated. This is wrong because the session cookie might have been renewed by a different tab.

**Comment by alexanderdean** [comment] 2015-07-09 11:11
Hey Fred - thanks for digging into this. It sounds like we can fix this, push a new version and then recheck the counts on Friday or Monday - is that a correct summary?

**Comment by fblundun** [comment] 2015-07-09 11:33
Hi Alex,

After talking to Yali and Christophe, we also thought we should make the following 2 changes:

* If cookies are disabled, then the sessionID should be regenerated after `sessionCookieTimeout` seconds of inactivity (rather than its current behaviour of staying the same until the page unloads)
* Similarly, if cookies are disabled, then the session index should increment after `sessionCookieTimeout` seconds of inactivity (rather than its current behaviour of staying at 1 for every event)

None of these 3 things should take too long so we should have a new version in test later today...

**Comment by alexanderdean** [comment] 2015-07-09 11:34
Sounds smart!

**Comment by fblundun** [comment] 2015-07-15 08:23
A while ago @yalisassoon raised the question of how likely it is for two duids to be the same purely by chance. I said that since the duid has 64 bits, we would need billions of events before a collision becomes likely.

But the duid actually has less than 64 bits of entropy since the it is a hash of the current time to the nearest second together with some browser features and the screen dimensions and colour depth (see the [source](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L524-L528)).

So the probability of two specific users who visit the site in the same second having the same duid is equal to the sum of the squares of the probabilities of all the different possible combinations of browser features.

We could get a first estimate of whether this probability is significant by finding the most common combination of browser features and calculating what proportion of duids have this combination.

The browser features used to calculate the hash are [these fields](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/outputs/EnrichedEvent.scala#L167-L177) plus `dvce_screenwidth` and `dvce_screenheight`.

**Comment by yalisassoon** [comment] 2015-07-16 10:16
Updated analysis on updated tracker version (with the above updates made):

**Virtually 100% of sessions identified by the new `domain_sessionid` field have only one session as identified using the old session definition (`domain_sessionidx` + `domain_userid`):

```sql
select  	
number_of_sessions_old_definition,  	
count(*) as frequency   	
from (  	
    select	
    domain_sessionid,	
    count(distinct(domain_userid || '-' || domain_sessionidx)) AS number_of_sessions_old_definition	
    from atomic.events	
    where collector_tstamp > '2015-07-07'	
    and domain_sessionid is not null	
	and v_tracker = 'js-2.5.0-m7'
    group by 1	
) t 	
group by 1  	
order by 1; 	
```
Returns:

```
1	6103
2	3
4	1
```
I.e. mappings of domain_sessionid -> 'domain_userid` + `domain_sessionid` is 1 to 1.

**However, `domain_userid` + `domain_sessionidx` combinations map to more than 1 `domain_sessionid` in 7% of use cases**

i.e. in 7% of sessions as identified by a `domain_userid` and `domain_sessionidx` combination, there will be more than one corresponding `domain_sessionid`. This means that the `domain_sessionid` is updating in some circumstances when the `domain_sessionidx` or `domain_userid` is not.

**Comment by yalisassoon** [comment] 2015-07-16 10:18
@fblundun - any ideas in what situations the `domain_sessionid` would update without the corresponding `domain_userid` or `domain_sessionidx` updating?

**Comment by fblundun** [comment] 2015-07-16 10:42
Thanks for the data @yalisassoon. Is there a specific browser in which the mismatch is more likely to happen?

**Comment by fblundun** [comment] 2015-07-16 10:53
It would could also be useful to know if mismatching is more likely to occur when the `domain_sessionidx` is 1, i.e. for a user's first visit when the cookies are initially created...

**Comment by yalisassoon** [comment] 2015-07-17 09:44
It's way more likely to occur when the `domain_sessionidx` is more than 1:

```sql
select
domain_sessionidx,
count(*) as frequency
from ( 
    select  
    domain_userid || '-' || domain_sessionidx,
	domain_sessionidx,
    count(distinct(domain_sessionid)) AS number_of_sessions_new_definition
    from atomic.events  
    where collector_tstamp > '2015-07-07'   
    and domain_sessionid is not null    
    and v_tracker = 'js-2.5.0-m7'
    group by 1,2
	having count(distinct(domain_sessionid)) > 1
) t
group by 1
order by 1
```

Returns:

```
1	4
2	132
3	81
4	49
5	27
6	20
7	18
8	12
9	10
10	8
...
```

**Comment by yalisassoon** [comment] 2015-07-17 09:47
On our website, it appears to effect mostly Chrome users - but I think most visitors to our website use Chrome:

```sql
select
br_name,
br_version,
count(*) as frequency
from ( 
    select  
    domain_userid || '-' || domain_sessionidx,
	br_name,
	br_version,
    count(distinct(domain_sessionid)) AS number_of_sessions_new_definition
    from atomic.events  
    where collector_tstamp > '2015-07-07'   
    and domain_sessionid is not null    
    and v_tracker = 'js-2.5.0-m7'
    group by 1,2,3
	having count(distinct(domain_sessionid)) > 1
) t
group by 1,2
order by 3 desc
```

Returns:

```
Chrome	43.0.2357.132	223
Chrome	43.0.2357.130	100
Chrome	43.0.2357.134	23
Safari	8.0.7	16
Chrome	43.0.2357.81	12
Chrome	43.0.2357.124	11
Safari	8.0.6	6
...
```

**Comment by yalisassoon** [comment] 2015-07-17 10:19
All right - I think I've figured out in what scenario the `domain_sessionid` incremends and the `domain_sessionidx` does not. It is on new sessions that start with a page ping. In these cases, it appears that the `domain_sessionid` will increment between the first ping and the second ping.

Manually inspecting data when the `domain_sessionidx` increments without an increment in `domain_sessionidx`:

```sql
select
problematic_records.domain_userid,
problematic_records.domain_sessionidx,
domain_sessionid,
dvce_tstamp,
collector_tstamp,
event,
page_urlpath
from ( 
    select  
    domain_userid,
	domain_sessionidx,
	count(distinct(domain_sessionid)) AS number_of_sessions_new_definition
    from atomic.events  
    where collector_tstamp > '2015-07-07'   
    and domain_sessionid is not null    
    and v_tracker = 'js-2.5.0-m7'
    group by 1,2
	having count(distinct(domain_sessionid)) > 1
) as problematic_records
join events
on problematic_records.domain_userid = events.domain_userid
and problematic_records.domain_sessionidx = events.domain_sessionidx
order by 1,2, dvce_tstamp
```

Returns data like this:

```
00796397fa90f9ae	2	49ef760a-d2c8-4ef4-85dd-30722f69e582	2015-07-14 20:47:35.688	2015-07-14 20:47:36	page_ping	/blog/2015/05/21/first-experiments-with-apache-spark/
00796397fa90f9ae	2	fabd6918-493e-429f-b84d-d8e045235314	2015-07-14 20:51:43.034	2015-07-14 20:51:43	page_ping	/blog/2015/05/21/first-experiments-with-apache-spark/
00796397fa90f9ae	2	fabd6918-493e-429f-b84d-d8e045235314	2015-07-14 20:54:49.291	2015-07-14 20:54:49	page_ping	/blog/2015/05/21/first-experiments-with-apache-spark/
00796397fa90f9ae	2	fabd6918-493e-429f-b84d-d8e045235314	2015-07-14 20:54:59.815	2015-07-14 20:55:00	page_ping	/blog/2015/05/21/first-experiments-with-apache-spark/
00796397fa90f9ae	2	fabd6918-493e-429f-b84d-d8e045235314	2015-07-14 20:58:30.811	2015-07-14 20:58:31	page_ping	/blog/2015/05/21/first-experiments-with-apache-spark/
00796397fa90f9ae	2	fabd6918-493e-429f-b84d-d8e045235314	2015-07-14 20:58:40.813	2015-07-14 20:58:41	page_ping	/blog/2015/05/21/first-experiments-with-apache-spark/
00796397fa90f9ae	2	fabd6918-493e-429f-b84d-d8e045235314	2015-07-14 20:58:48.074	2015-07-14 20:58:48	unstruct	/blog/2015/05/21/first-experiments-with-apache-spark/
...
0097e375faacb90f	4	147fc632-0279-416f-9fae-10feeb4a046b	2015-07-11 01:08:52.813	2015-07-11 01:08:53	page_ping	/blog/2015/07/05/schema-guru-0.2.0-released/
0097e375faacb90f	4	fdbe9398-9e02-4007-8f3a-efdc53365fce	2015-07-11 01:09:03.347	2015-07-11 01:09:03	page_ping	/blog/2015/07/05/schema-guru-0.2.0-released/
0097e375faacb90f	4	fdbe9398-9e02-4007-8f3a-efdc53365fce	2015-07-11 01:09:04.338	2015-07-11 01:09:04	page_ping	/blog/2015/07/02/visualizing-marketing-attribution-data-with-d3js/
0097e375faacb90f	4	fdbe9398-9e02-4007-8f3a-efdc53365fce	2015-07-11 01:09:14.329	2015-07-11 01:09:14	page_ping	/blog/2015/07/02/visualizing-marketing-attribution-data-with-d3js/
0097e375faacb90f	4	fdbe9398-9e02-4007-8f3a-efdc53365fce	2015-07-11 01:09:14.33	2015-07-11 01:09:14	page_ping	/blog/2015/07/05/schema-guru-0.2.0-released/
0097e375faacb90f	4	fdbe9398-9e02-4007-8f3a-efdc53365fce	2015-07-11 01:09:24.337	2015-07-11 01:09:24	page_ping	/blog/2015/07/02/visualizing-marketing-attribution-data-with-d3js/
0097e375faacb90f	4	fdbe9398-9e02-4007-8f3a-efdc53365fce	2015-07-11 01:09:35.34	2015-07-11 01:09:35	page_ping	/blog/2015/07/05/schema-guru-0.2.0-released/
01cea3b3a7210d28	2	14f4fbf6-290a-40dd-ac10-af15b0202d20	2015-07-16 05:54:49.579	2015-07-16 05:54:48	page_ping	/analytics/recipes/catalog-analytics/market-basket-analysis-identifying-products-that-sell-well-together.html
01cea3b3a7210d28	2	d95bb24c-f33f-4dff-81ac-9e7c8737816c	2015-07-16 05:56:39.591	2015-07-16 05:56:38	page_ping	/analytics/recipes/catalog-analytics/market-basket-analysis-identifying-products-that-sell-well-together.html
01cea3b3a7210d28	2	d95bb24c-f33f-4dff-81ac-9e7c8737816c	2015-07-16 06:01:50.13	2015-07-16 06:01:49	page_view	/analytics/recipes/catalog-analytics/market-basket-analysis-identifying-products-that-sell-well-together.html
...
0203fb550713aed0	3	e4eec4e5-a217-477d-9f8c-4e2312aedbff	2015-07-10 18:03:58.202	2015-07-10 18:04:08	page_ping	/blog/2014/11/26/snowplow-0.9.12-released-with-real-time-load-into-elasticsearch-beta/
0203fb550713aed0	3	03338b05-3dc5-4b62-8a5f-f906c6a981c8	2015-07-10 18:04:08.20	2015-07-10 18:04:18	page_ping	/blog/2014/11/26/snowplow-0.9.12-released-with-real-time-load-into-elasticsearch-beta/
0203fb550713aed0	3	03338b05-3dc5-4b62-8a5f-f906c6a981c8	2015-07-10 18:04:18.201	2015-07-10 18:04:28	page_ping	/blog/2014/11/26/snowplow-0.9.12-released-with-real-time-load-into-elasticsearch-beta/
...
```

**Comment by yalisassoon** [comment] 2015-07-17 10:20
If the above is right, the in the above examples the `domain_sessionid` is incrementing when it should not, and we should fix this before pushing the new JS release

**Comment by fblundun** [comment] 2015-07-17 16:38
So far the only way I have been able to reproduce multiple sids for a single duid+vid combination is:

* Load a page using version 2.4.0
* Change the page to use 2.5.0
* Load the changed page in a separate tab and fire an event
* Go to the first tab and fire an event (this will remove the sid from the cookie since 2.4.0 doesn't know about sids)
* Return to the second tab and fire an event (the tracker will get the vid from the cookie but will have to generate a new sid.)

I don't think this can be responsible for the mismatching we have seen in real life - it would be pretty surprising for such a high percentage of users to still have an old tab open from when version 2.4.0 was on the website.

So I will keep trying to work out what really is responsible...

**Comment by fblundun** [comment] 2015-07-20 14:22
I think I've found the true cause.

Each tracker instance has a boolean "configWriteCookies" configuration option. This isn't intended to be set by the user - instead it gets set by the tracker itself. "configWriteCookies" is set to `true` for the first tracker instance you create and `false` for each subsequent one. The idea is that it is only necessary for one tracker instance to write cookies - the other two can just read them.

If page pings are enabled, each tracker instance has its own repeating page ping (created using `setInterval`). Ideally these page pings would always occur in the same sequence (snplow2, snplow1, snplow5 on our website). But in reality, these intervals can desynchronize so that the second tracker instance sends page pings very slightly before the first tracker instance. This is problematic if a new session has begun, since the second tracker instance will see that the session cookie has expired and create a session ID but won't write that ID to the ID cookie or create a new session cookie. Then the first tracker creates a new session ID and writes it to the ID cookie, and the second tracker instance then reads this new session ID and starts using it for its own events.

I think the simplest solution is to drop the "configWriteCookies" setting and have all tracker instances able to write cookies. The cookies are only mutated if the session cookie isn't set, any mutation causes the session cookie to be set, so we are safe from two tracker instances simultaneously mutating the ID cookie.

**Comment by alexanderdean** [comment] 2015-07-20 15:08
Great sleuthing, sounds like a practical soln

**Comment by yalisassoon** [comment] 2015-07-22 10:16
Just tested the updated version and it's working great!

Each session as identified by the new `domain_sessionidx` corresponds to a single `domain_userid` + `domain_sessionidx` combination:

```sql
select      
number_of_sessions_old_definition,      
count(*) as frequency       
from (      
    select  
    domain_sessionid,   
    count(distinct(domain_userid || '-' || domain_sessionidx)) AS number_of_sessions_old_definition 
    from atomic.events  
    where collector_tstamp > '2015-07-07'   
    and domain_sessionid is not null    
    and v_tracker = 'js-2.5.0-m8'
    group by 1  
) t     
group by 1      
order by 1;  
```

Returns:

```
1	1657
```

Only a very small percentage (<0.7%) of sessions identified by the old `domain_userid` + `domain_sessionidx` definition correspond to more than one `domain_sessionid`:

```sql
select      
number_of_sessions_new_definition,      
count(*) as frequency       
from (      
    select  
    domain_userid || '-' || domain_sessionidx,  
    count(distinct(domain_sessionid)) AS number_of_sessions_new_definition  
    from atomic.events  
    where collector_tstamp > '2015-07-07'   
    and domain_sessionid is not null    
    and v_tracker = 'js-2.5.0-m8'
    group by 1  
) t     
group by 1      
order by 1;  
```

Returns:

```sql
1	1526
2	2
3	1
4	1
12	1
15	3
17	1
46	1
```

I think we're good to push the release!

**Comment by alexanderdean** [comment] 2015-07-22 11:11
Great! Fixed, closing

**Closed by alexanderdean** 2015-07-22 11:11 UTC
Labels: question
