### ISSUE TITLE
Create a unique page view ID on page load, and send this event as context with each subsequent event

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#346] opened 2015-03-20 10:47 UTC
This will make it easy at analysis time to tie events that happened in-page back to the specific page view they were part of.

The ID should be sent as part of an 'ancestry context' that might also include a session index and user id(s) fields.

**Comment by fblundun** [comment] 2016-06-07 14:24
Closing as duplicate of #369

**Closed by fblundun** 2016-06-07 14:24 UTC
Labels: Enhancement
